dubbo.application.name=qiyu-live-im-router-provider
dubbo.registry.address=nacos://127.0.0.1:8848?username=${NACOS_USERNAME:nacos}&password=${NACOS_PASSWORD:}&namespace=public
dubbo.server=true
dubbo.protocol.name=dubbo
dubbo.protocol.port=9095
